services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - backend/.env      
      - frontend/.env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: